In [150]:
import lancedb
from sentence_transformers import SentenceTransformer
import json
import os
import pandas as pd
from openai import OpenAI
import re

In [177]:
DB_PATH = "/home/linux/linux/ProjectsReal/chef/scripts/lancedb"
TABLE_NAME = "recepies"

EMBED_MODEL = "all-MiniLM-L6-v2"
TOP_K = 10

In [63]:
# -----------------------------
# LOAD EMBEDDING MODEL
# -----------------------------
print("🔄 Loading embedding model...")
model = SentenceTransformer(EMBED_MODEL)

🔄 Loading embedding model...

Loading weights: 100%|█████████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 3443.38it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [64]:
def load_table():
	db = lancedb.connect(DB_PATH)
	return db.open_table(TABLE_NAME)

In [65]:
def parse_chatgpt_json(response: str):
    # Remove markdown code block if present
    cleaned = re.sub(r"```json|```", "", response).strip()
    
    return json.loads(cleaned)

In [184]:
# -----------------------------
# SEARCH FUNCTION
# -----------------------------
def search(table, query, top_k=5):
	# print(f"\n🔍 Query: {query}")

	query_embedding = model.encode(query).tolist()

	results = (
		table.search(query_embedding)
		.limit(top_k)
		.to_list()
	)

	return results

In [67]:
# -----------------------------
# DISPLAY RESULTS
# -----------------------------
def display_results(results):
    for i, r in enumerate(results):
        print(r)
        # print(r["text"])  # print first 500 chars
        print("\n")

In [185]:
def quertingLance(query):
    table = load_table()
    results = search(table, query, TOP_K)
    return results
	# display_results(results)

In [121]:
def truncate_response(query, answers_list):
    truncated_answer = []
    for answer in answers_list:
        answer_dict = {}
        answer_dict['query'] = query
        answer_dict['id'] = answer['id']
        answer_dict['text'] = answer['text']
        answer_dict['distance'] = answer['_distance']
        truncated_answer.append(answer_dict)
    return truncated_answer

In [189]:
# query = "breakfast with less than 5 minutes prep time?"
# query = "high protien low carbohydrates breakfast"
# query = "tomatoes and basil"
# query =  "dinner, quick, easy, low prep, fast"
query = "doemon shinchan pikcahu hayabusa"
query_response = quertingLance(query)
print(query_response)

[{'id': 381, 'recepie name': 'Nankhatais (Indian Cookies)', 'ingredients': ['150 gms flour', '100 gms ghee or clarified butter', '115 gms fine sugar', '1/8 tsp baking powder', '1/4 cup milk', '5 cardamoms, powdered', 'rose essence', 'blanched, chopped almonds or pistachios'], 'directions': ['Sift flour and baking powder.', 'Add sugar and mix well.', 'Work in ghee, cardamom powder and rose essence.', 'Add milk and knead to a soft dough.', 'Shape dough into small balls and press gently.', 'Garnish with chopped almonds or pistachios.', 'Bake in preheated moderate oven (180 degrees C) for 20 minutes or until golden brown.'], 'tags': ['Indian', 'Cookies', 'Baked', 'Sweet', 'Snack', 'Vegetarian', 'Dessert'], 'prep time': '15 minutes', 'cook time': '20 minutes', 'yield': 'About 20 cookies', 'cook time minutes': 20, 'prep time minutes': 20, 'per serving': 'Approximately 1 cookie', 'note': '', 'tip': '', 'vary it': 'For Mexican cookies, add half the quantity of sugar. Roll nankhatai dough into 1 inch balls. Place on greased baking sheet and flatten slightly. After baking, roll in icing sugar whilst still warm. Let cool, roll again in icing sugar.', 'text': 'Nankhatais (Indian Cookies) ingredients =  150 gms flour 100 gms ghee or clarified butter 115 gms fine sugar 1/8 tsp baking powder 1/4 cup milk 5 cardamoms, powdered rose essence blanched, chopped almonds or pistachios directions =  Sift flour and baking powder. Add sugar and mix well. Work in ghee, cardamom powder and rose essence. Add milk and knead to a soft dough. Shape dough into small balls and press gently. Garnish with chopped almonds or pistachios. Bake in preheated moderate oven (180 degrees C) for 20 minutes or until golden brown. tags =  Indian Cookies Baked Sweet Snack Vegetarian Dessert prep time =  15 minutes cook time =  20 minutes yield =  About 20 cookies per serving =  Approximately 1 cookie variation =  For Mexican cookies, add half the quantity of sugar. Roll nankhatai dough into 1 inch balls. Place on greased baking sheet and flatten slightly. After baking, roll in icing sugar whilst still warm. Let cool, roll again in icing sugar.', 'embedding': [-0.047437358647584915, -0.02405569516122341, -0.023582670837640762, -0.017768587917089462, -0.0781543180346489, -0.07923956215381622, 0.033562853932380676, -0.005668453872203827, -0.029309282079339027, -0.011379378847777843, 0.03319169580936432, -0.07727646827697754, -0.044699229300022125, -0.060613665729761124, 0.11571405827999115, -0.04350224509835243, 0.057519733905792236, 0.00403956975787878, -0.02716127224266529, -0.04387333616614342, 0.07900795340538025, -0.05124366655945778, 0.05203688144683838, 0.055859073996543884, -0.017032001167535782, -0.029095537960529327, 0.08614545315504074, -0.06019742414355278, 0.002570868469774723, -0.03910151496529579, 0.005347284954041243, 0.040310878306627274, 0.024562332779169083, -0.03221519663929939, -0.02699459344148636, 0.03472568094730377, -0.01471739448606968, -0.008227594196796417, -0.03246365115046501, -0.07008656114339828, 0.012769537046551704, 0.06018250435590744, 0.08223412185907364, -0.03243209421634674, 0.00010999126971000805, 0.01522140670567751, -0.019971981644630432, -0.03157087787985802, -0.0002202504692832008, -0.02420002594590187, -0.037242911756038666, -0.022825682535767555, -0.0021120477467775345, -0.027082033455371857, -0.03835037723183632, -0.07096841186285019, -0.10476531088352203, -0.03827318549156189, -0.0382184274494648, 0.066757433116436, -0.04317809268832207, 0.06813579052686691, 0.04086142033338547, -0.040178317576646805, 0.03640133515000343, -0.024763576686382294, -0.04813741147518158, -0.06087629124522209, -0.01892547495663166, 0.005102851428091526, -0.03621862083673477, 0.02581002376973629, 0.009268682450056076, 0.021976066753268242, -0.11928345263004303, -0.030924344435334206, 0.1087968498468399, -0.018272096291184425, -0.03142590820789337, -0.004501949530094862, -0.05724138393998146, 0.022303208708763123, 0.08783338963985443, 0.07923886179924011, -0.012416520155966282, -0.01907900720834732, 0.04139989614486694, 0.13967588543891907, 0.07284945249557495, -0.01251165196299553, 0.1297895461320877, 0.10198846459388733, -0.04688894376158714, 0.05718085914850235, -0.05110863968729973, -0.016255345195531845, 0.002528878627344966, -0.000377459276933223, 0.022199096158146858, 0.03452063724398613, 0.025477131828665733, 0.029309771955013275, -0.0031051901169121265, -0.04754992201924324, -0.12679390609264374, 0.017121437937021255, 0.05052727460861206, -0.02330169454216957, 0.06444267928600311, 0.1130489930510521, 0.02275175414979458, 0.06001628190279007, 0.031665876507759094, -0.0011369233252480626, -0.13157625496387482, -0.014032578095793724, -0.00022456154692918062, -0.014084910973906517, 0.0027603204362094402, 0.0016595091437920928, -0.047279104590415955, 0.021178653463721275, 0.040788087993860245, 0.01467310730367899, -0.033251333981752396, 0.005785489920526743, 0.0018030006904155016, 7.027497550455222e-33, -0.027820758521556854, 0.06884203106164932, -0.008326048962771893, -0.03683209419250488, -0.03518650308251381, 0.01763654127717018, -0.020835865288972855, -0.018078764900565147, -0.02663075365126133, 0.01015402190387249, -0.04083971306681633, -0.0073029519990086555, -0.06944822520017624, 0.02589225210249424, -0.05273548886179924, -0.022319210693240166, -0.005481243133544922, -0.04342396557331085, 0.062025994062423706, -0.006439428310841322, -0.04701441898941994, 0.006811116356402636, -0.008901158347725868, 0.0004114485054742545, -0.07369565963745117, 0.0779583677649498, -0.04694145917892456, 0.009719064459204674, -0.04602205753326416, 0.01635393686592579, 0.12898284196853638, -0.0759122222661972, -0.09673741459846497, -0.026394294574856758, 0.008686015382409096, 0.01974327862262726, -0.011565984226763248, 0.05498876795172691, -0.028033394366502762, 0.016790494322776794, 0.011215361766517162, 0.014605768956243992, 0.0010789697989821434, -0.0039041710551828146, -0.08351626992225647, -0.03316640481352806, 0.014776854775846004, 0.11021872609853745, 0.10917453467845917, 0.04009607061743736, -0.061903875321149826, 0.0043589770793914795, 0.011630957946181297, 0.052269186824560165, -0.02911694534122944, -0.06281882524490356, 0.06119305267930031, -0.04814733564853668, -0.05150905251502991, -0.008209828287363052, 0.006415147799998522, -0.0669744461774826, -0.04515044018626213, -0.07740029692649841, -0.04001311585307121, -0.002212204271927476, 0.023170050233602524, 0.09191030263900757, 0.008668068796396255, -0.06743641942739487, -0.005070746876299381, -0.0755700096487999, 0.07501967251300812, -0.036206528544425964, -0.06117673218250275, -0.019845014438033104, 0.07651514559984207, 0.019131159409880638, 0.022169889882206917, 0.08619166910648346, 0.06970065832138062, 0.010606547817587852, -0.0457843579351902, -0.04445705935359001, -0.04997273534536362, 0.04227009415626526, -0.016995234414935112, 0.054270189255476, 0.020520981401205063, 0.0038149587344378233, -0.00820236187428236, -0.031012581661343575, 0.08818769454956055, 0.03861304745078087, -0.07631814479827881, -7.013786143536849e-33, -0.016068534925580025, -0.02087388187646866, -0.03339855745434761, 0.0410761833190918, 0.05123848468065262, -0.05744710564613342, 0.0955602154135704, 0.025373591110110283, 0.01087086834013462, -0.08465004712343216, 0.01641779951751232, -0.057261932641267776, 0.05346861109137535, 0.0028072260320186615, -0.026229094713926315, 0.07442714273929596, 0.04451122134923935, 0.14730136096477509, -0.01272568479180336, -0.09256049990653992, -0.04023528844118118, 0.12700872123241425, -0.055659063160419464, 0.045157235115766525, 0.05285012722015381, 0.099422886967659, 0.08234798908233643, 0.08166716247797012, -0.038217220455408096, 0.027775876224040985, 0.03958931192755699, -0.06302960216999054, -0.010193660855293274, -0.015565532259643078, -0.021193230524659157, -0.03812108188867569, 0.025459660217165947, 0.031932808458805084, -0.057657428085803986, -0.009143074043095112, -0.04534895718097687, 0.04077771678566933, 0.01821446418762207, -0.029321663081645966, -0.0183709766715765, 0.05670616403222084, 0.02261977456510067, 0.026316221803426743, -0.037046436220407486, 0.0663537085056305, 0.016831396147608757, -0.04783681035041809, -0.04766897112131119, -0.04213845357298851, 0.005718748085200787, 0.05001364275813103, -0.06048709154129028, -0.03233174979686737, -0.01186460629105568, -0.12227408587932587, -0.07933711260557175, -0.013352787122130394, 0.08697543293237686, -0.03137978911399841, 0.009038392454385757, 0.0531790666282177, 0.04215918481349945, 0.005398209672421217, 0.09051549434661865, 0.058285903185606, -0.08792572468519211, 0.0719153955578804, 0.04392232373356819, -0.02928900346159935, 0.0029713294934481382, 0.04671446979045868, 0.05176877975463867, -0.08832647651433945, 0.04792359471321106, -0.08906523883342743, 0.003002679906785488, 0.05951362103223801, 0.020922722294926643, -0.014321478083729744, 0.017626088112592697, 0.09866244345903397, -0.039901088923215866, 0.035924170166254044, 0.03968142718076706, 0.00967289600521326, -0.02745758555829525, 0.05832495912909508, 0.08017218858003616, 0.07436342537403107, -0.0013066856190562248, -4.233392658647972e-08, 0.023211687803268433, -0.12906503677368164, -0.04332356154918671, 0.0441635400056839, 0.00117325852625072, 0.04036874324083328, 0.008011790923774242, -0.026455452665686607, -0.008605937473475933, -0.06081879511475563, 0.07160881906747818, 0.09900446981191635, -0.022774815559387207, 0.049440898001194, -0.07105718553066254, -0.05288368836045265, 0.057476140558719635, 0.07312756031751633, -0.01637711189687252, -0.1138557717204094, -0.048318225890398026, -0.02979966439306736, 0.027074573561549187, -0.05478725954890251, 0.011002876795828342, 0.03212331235408783, -0.038834650069475174, 0.04617485776543617, 0.004148164298385382, -0.046773511916399, -0.08260542154312134, -0.002773676998913288, 0.015284720808267593, 0.0069127557799220085, 0.020038580521941185, 0.003587523242458701, -0.057437535375356674, -0.028188662603497505, -0.03698713704943657, -0.03012298420071602, 0.034558478742837906, -0.01527410838752985, 0.03368449956178665, -0.014175607822835445, -0.006473332177847624, -0.07330915331840515, -0.0650462657213211, 0.05319549888372421, -0.0036508110351860523, 0.07876414805650711, -0.014785838313400745, -0.00558518385514617, -0.057573407888412476, 0.03222334757447243, 0.01802034303545952, -0.07570702582597733, -0.03899305313825607, -0.028047122061252594, 0.04516163840889931, -0.012627013027668, 0.0369630828499794, -0.055619556456804276, -0.016118988394737244, -0.09563131630420685], '_distance': 1.5171098709106445}, {'id': 301, 'recepie name': 'Lo Han Chai', 'ingredients': ['1 cup parboiled vegetables (carrots, peas, corn, capsicum, etc.)', '1 cup canned foodstuff (mushrooms, gluten, bamboo shoots, etc.)', '100 gms white fungus soaked in water and chopped', '150 ml water', '1/2 tsp salt', '2 tsps cornstarch', '2 tbsps soya sauce', 'pinch of ajinomoto', 'chilli sauce to taste', '5 tbsps oil'], 'directions': ['Sauté mushrooms in oil for a minute or two.', 'Add all the vegetables and fungus.', 'Stir fry for another two minutes.', 'Add soya sauce, ajinomoto, chilli sauce and salt.', 'Stir and add water and cornstarch.', 'Simmer for 2 minutes stirring constantly.', 'When the sauce thickens, remove from heat and transfer on a platter.'], 'tags': ['main dish', 'vegetarian', 'Chinese cuisine', 'stir fry', 'vegetables', 'sauce'], 'prep time': '', 'cook time': '', 'yield': 'serves 4', 'cook time minutes': 0, 'prep time minutes': 0, 'per serving': '', 'note': '', 'tip': '', 'vary it': '', 'text': 'Lo Han Chai ingredients =  1 cup parboiled vegetables (carrots, peas, corn, capsicum, etc.) 1 cup canned foodstuff (mushrooms, gluten, bamboo shoots, etc.) 100 gms white fungus soaked in water and chopped 150 ml water 1/2 tsp salt 2 tsps cornstarch 2 tbsps soya sauce pinch of ajinomoto chilli sauce to taste 5 tbsps oil directions =  Sauté mushrooms in oil for a minute or two. Add all the vegetables and fungus. Stir fry for another two minutes. Add soya sauce, ajinomoto, chilli sauce and salt. Stir and add water and cornstarch. Simmer for 2 minutes stirring constantly. When the sauce thickens, remove from heat and transfer on a platter. tags =  main dish vegetarian Chinese cuisine stir fry vegetables sauce yield =  serves 4', 'embedding': [-0.0943419560790062, -0.01948058418929577, 0.04216192662715912, -0.02513614296913147, 0.01571843959391117, -0.06677515804767609, -0.00842105969786644, -0.029074490070343018, 0.054550498723983765, -0.13956700265407562, 0.08833324909210205, -0.08465629070997238, 0.028921855613589287, -0.08903507888317108, -0.006615231279283762, -0.028389310464262962, 0.09791159629821777, 0.03905234485864639, -0.0593026764690876, -0.123655304312706, 0.0417928583920002, -0.0049843392334878445, 0.034661706537008286, 0.012055628001689911, -0.05509979650378227, -0.06466034799814224, 0.06724146008491516, 0.03704769164323807, -0.10252077132463455, -0.05773786082863808, 0.02570917457342148, 0.07865362614393234, -0.0705430656671524, -0.036887429654598236, -0.06608060747385025, 0.005710971541702747, 0.0032398123294115067, -0.05655818060040474, 0.0724029541015625, 0.02639109268784523, 0.05896971374750137, -0.044288598001003265, 0.15357349812984467, -0.07131388783454895, 0.11894477158784866, 0.03441433981060982, -0.0881950706243515, -0.031618524342775345, 0.06861181557178497, -0.04083997756242752, -0.07995066791772842, 0.001092860591597855, 0.08876777440309525, -0.03327036276459694, -0.02743850089609623, 0.01759105920791626, -0.07670695334672928, 0.005421835463494062, 0.025017330422997475, 0.09055012464523315, -0.05415991693735123, 0.017500359565019608, 0.030257243663072586, -0.028191648423671722, -0.03621508181095123, -0.11100244522094727, -0.01548647228628397, -0.019681144505739212, 0.005948849022388458, 0.06619556993246078, -0.03872954472899437, 0.015047026798129082, 0.018971841782331467, 0.038288503885269165, -0.019722428172826767, 0.03012016788125038, 0.02880771830677986, -0.03624332696199417, 0.02583468332886696, -0.04026591405272484, 0.012276502326130867, 0.04482502117753029, 0.03585471585392952, 0.05459672585129738, 0.02862883359193802, 0.026829056441783905, 0.032228436321020126, -0.011487011797726154, 0.032808542251586914, 0.026679137721657753, 0.046702031046152115, 0.06886114925146103, -0.05744548141956329, -0.004920605570077896, -0.01112911943346262, 0.021069735288619995, 0.042452022433280945, -0.08488235622644424, -0.07358312606811523, 0.03217395395040512, -0.01631055772304535, -0.06032709777355194, 0.01602175086736679, -0.0878085196018219, -0.04553525149822235, 0.02250523492693901, 0.04176050052046776, -0.025722352787852287, 0.036029964685440063, 0.026293326169252396, 0.009647506289184093, 0.039326515048742294, -0.07089246809482574, -0.09649164974689484, 0.017153743654489517, -0.01044673752039671, 0.0864790678024292, -0.03416334465146065, -0.02255971170961857, -0.07423960417509079, -0.0032913205213844776, -0.013839028775691986, -0.03208141028881073, 0.0037104717921465635, -0.04818812012672424, -0.01711283065378666, 0.04324069991707802, 7.390382942129632e-33, 0.05832146108150482, 0.03996013477444649, -0.05137554183602333, -0.037461765110492706, -0.04441851004958153, -0.07809298485517502, -0.009542391635477543, 0.032586146146059036, -0.043167561292648315, -0.005663194693624973, -0.015709031373262405, -0.04423646256327629, -0.05178732052445412, 0.013005551882088184, -0.018984686583280563, -0.09016704559326172, 0.06062150001525879, 0.0006401260616257787, 0.05160043388605118, -0.0672256126999855, 0.040149129927158356, 0.016507919877767563, 0.03394981846213341, -0.0518190972507, -0.03257928788661957, 0.009402472525835037, 0.01949055679142475, -0.10653649270534515, -0.04514533281326294, 0.02231736108660698, 0.027963217347860336, 0.019547533243894577, -0.07677245140075684, -0.003724676324054599, -0.019700761884450912, 0.010090949945151806, -0.02790306881070137, 0.03476322442293167, -0.0020815383177250624, 0.03410959988832474, -0.038685183972120285, 0.053841881453990936, -0.02556600235402584, 0.025609176605939865, -0.049143318086862564, 0.0452113002538681, 0.007926561869680882, 0.02725200355052948, 0.05689041316509247, 0.06206947937607765, -0.027745084837079048, -0.012467104010283947, 0.027967732399702072, 0.0117007065564394, 0.009489402174949646, 0.0004540033114608377, 0.07990318536758423, -0.04073704034090042, 0.026139648631215096, -0.027175940573215485, -0.05751422420144081, 0.03916952759027481, -0.1297709345817566, -0.03513174504041672, -0.04880392923951149, 0.037113722413778305, -0.08656278252601624, -0.06704487651586533, 0.03943145275115967, -0.024674538522958755, 0.02535823918879032, -0.046239688992500305, 0.00040951554547064006, 0.008768352679908276, -0.02919801138341427, -0.04700672999024391, -0.017754867672920227, 0.022301537916064262, -0.003915879875421524, 0.08847473561763763, 0.10495423525571823, -0.029248449951410294, 0.008548174984753132, 0.0356430783867836, -0.023108603432774544, 0.04559716582298279, -0.03575402498245239, 0.09084182232618332, 0.09846561402082443, -0.034799907356500626, -0.026569871231913567, -0.09553901106119156, 0.13322213292121887, -0.03400108963251114, -0.051886655390262604, -6.518886124109373e-33, 0.0182711910456419, -0.008299509063363075, 0.004537262488156557, 0.127264142036438, 0.03583594784140587, -0.0732257068157196, 0.0192416924983263, 0.05434459447860718, 0.08069117367267609, -0.06782266497612, -0.03697105124592781, -0.07286036014556885, 0.012428204528987408, -0.06402986496686935, -0.009415164589881897, 0.06337630748748779, -0.04775312542915344, 0.1480024755001068, -0.005356609355658293, 0.0687224268913269, 0.00048385263653472066, 0.01249467208981514, 0.047427836805582047, 0.0654914453625679, 0.030759107321500778, 0.026969997212290764, 0.1211579367518425, 0.03722521662712097, -0.07851788401603699, 0.011579598300158978, 0.004051738418638706, -0.10692527145147324, -0.008693994022905827, -0.03680375963449478, -0.00829161237925291, -0.05326514318585396, -0.01708824932575226, -0.006076265126466751, -0.009548024274408817, 0.029093250632286072, 0.006801694165915251, -0.025702061131596565, -0.01359543763101101, 0.10210761427879333, -0.02363687753677368, -0.013676594011485577, -0.00892434548586607, -0.023034129291772842, -0.03728087991476059, 0.06672495603561401, 0.02104143425822258, -0.07093699276447296, -0.0007583295810036361, -0.0841105654835701, -0.006809970363974571, -0.033873558044433594, 0.06566639244556427, 0.002847506431862712, -0.0017542417626827955, -0.06070052087306976, -0.043805286288261414, 0.02715251035988331, 0.013302442617714405, -0.00964336283504963, 0.04142133146524429, 0.08991598337888718, 0.037574708461761475, -0.028270935639739037, 0.04740606248378754, 0.012899934314191341, 0.01106248889118433, 0.008985878899693489, 0.09274271130561829, -0.025481482967734337, 0.05013364553451538, -0.03386669605970383, -0.02994181588292122, 0.026729721575975418, 0.04323838651180267, 0.05718258395791054, 0.009827814064919949, -0.0068865008652210236, 0.003252520225942135, -0.012873269617557526, 0.04082837700843811, 0.040597863495349884, -0.020715445280075073, 0.07227230817079544, 0.04604575037956238, 0.01950233243405819, 0.01277079340070486, -0.013827426359057426, 0.08168648928403854, 0.10612687468528748, 0.06291896104812622, -4.332653347205451e-08, 0.06133158877491951, -0.07792006433010101, -0.053879912942647934, 0.05971547216176987, -0.0427597239613533, 0.01331774890422821, 0.04064692184329033, -0.022128062322735786, 0.06430136412382126, -0.07562307268381119, 0.028527671471238136, 0.18010078370571136, -0.020012039691209793, 0.061408307403326035, -0.02471659518778324, -0.01988302357494831, 0.034445371478796005, 0.060435015708208084, -0.005245649255812168, 0.013128673657774925, 0.02589256502687931, 0.00028243125416338444, 0.034644823521375656, -0.02006063424050808, 0.08681033551692963, 0.011937648057937622, -0.04192459210753441, 0.049606505781412125, 0.0008665156783536077, -0.07691068202257156, -0.0361

In [93]:
df = pd.read_csv('/home/linux/linux/ProjectsReal/chef/validation.csv')

In [94]:
df.head()

                      Query   query type
0       Paneer curry recipe  ingredients
1  food items made with dal  ingredients
2     Indian Style Sandwich  ingredients
3      french fries recipes  ingredients
4    french onion soup tips  ingredients

In [122]:
full_results = []
for index, row in df.iterrows():
    query = row['Query']
    # print(query)
    query_response = quertingLance(query)
    # print(query_response)
    truncated = truncate_response(query, query_response)
    full_results = full_results + truncated

In [123]:
full_df = pd.DataFrame(full_results)

In [124]:
full_df.head()

,query,id,text,distance
0,Paneer curry recipe,309,Paneer Tikka ingredients = 500 gms home-made ...,0.582293
1,Paneer curry recipe,324,Garbanzos and Potato Curry ingredients = 1 ti...,0.836615
2,Paneer curry recipe,293,thai coconut curry ingredients = 150 gms long...,0.878080
3,Paneer curry recipe,343,Baked Curry Rice ingredients = 3 cups long gr...,0.887982
4,Paneer curry recipe,305,Yogurt Curry ingredients = 8-10 chick pea flo...,0.904629

In [125]:
full_df.to_csv("/home/linux/linux/ProjectsReal/chef/validation_extracted.csv", index=False)

# Validation

In [132]:
api_key = ""
client = OpenAI(api_key=api_key)

In [156]:
df = pd.read_csv('/home/linux/linux/ProjectsReal/chef/validation_extracted.csv')

In [157]:
df.head()

,query,text,distance,id
0,Paneer curry recipe,Paneer Tikka ingredients = 500 gms home-made ...,0.582293,309
1,Paneer curry recipe,Garbanzos and Potato Curry ingredients = 1 ti...,0.836615,324
2,Paneer curry recipe,thai coconut curry ingredients = 150 gms long...,0.878080,293
3,Paneer curry recipe,Baked Curry Rice ingredients = 3 cups long gr...,0.887982,343
4,Paneer curry recipe,Yogurt Curry ingredients = 8-10 chick pea flo...,0.904629,305

In [158]:
KNOWLEDGE_BASE = """
You are a recipe writer. you need to evaluate whether the recipe is related or not to the keyword and provide scores.
This is a part of a RAG system evaluation and I want to evaluate the system performance and accuracy.

Relevance:
Ensure the recipe is concise and relevant to the keyword
Give a score between 1 to 10 with 1 being least relevant and 10 being the most relevant.


Groundedness
Ensure the recipe is grounded in the keywords.
Ensure the recipe does not contain "hallucinated" information outside the scope of the keywords.
to what extent does the generated response agree with the retrieved context. 
give a score between 1 to 10 with 1 being least grounded and 10 being the most grounded.


relatedness:
You goal is to identify recipes which completely unrelated to the keyword
(2) If the recipe contains ANY words or semantic meaning related to the keyword, consider them related
It is OK if the recipe has SOME information that is unrelated to the keyword as long as (2) is met
give a score between 1 to 10 with 1 being least related and 10 being the most related.


semantic similarity:
rate semantic similarity between the keyword and the recipe with 10 being high semantic match and 1 being the lowest semantic match

Required Response:

{    
    "relevance"; score,
    "groundedness": score,
    "relatedness": score,
    "semantic match"; score
}

the score should strictly be as mentioned.
The response should strictly contain the keys and format as mentioned.
Please double check the response


    Return JSON.
"""

def extract_timeline(recipe, keyword):
    response = client.chat.completions.create(
        model="gpt-4.1-mini",  # fast + cheap + good for extraction
        temperature=0,
        messages=[
            {
                "role": "system",
                "content": KNOWLEDGE_BASE
            },
            {
                "role": "user",
                "content": f"Keyword:\n{keyword}  Recipe:\n{recipe}"
            }
        ]
    )

    result = response.choices[0].message.content
    return result
    # if result:
        # return json.loads(result)
    # return None

In [159]:
def parse_chatgpt_json(response: str):
    # Remove markdown code block if present
    cleaned = re.sub(r"```json|```", "", response).strip()
    return json.loads(cleaned)

In [160]:
keyw = "vegetarian soup recipes"
# recipetext = "Paneer Tikka ingredients =  500 gms home-made cottage cheese or paneer 1 thumb-size piece ginger 4 cloves garlic, minced 1 small onion, chopped Juice of one lemon 1/4 tsp black cumin seeds 1 whole cardamom, crushed 1/4 tsp powdered cloves 1/4 tsp powdered cinnamon 1/4 tsp chilli powder 2 tbsps tomato paste 1 cup yogurt 2 tbsps cream cheese Ghee or butter 1/4 cup fresh coriander, chopped directions =  Blend onion, ginger, garlic in blender. Blend further to a smooth paste with cream cheese and yogurt. Mix in all the ingredients. Cut cheese in cubes and marinate in yogurt mixture. Let stand for half an hour in a large saucepan. Heat on a very low flame for 15 minutes. Turn onto a serving platter, dot with butter and garnish with chopped coriander. Serve hot. tags =  main dish vegetarian Indian cuisine spicy dinner snack grilled appetizer prep time =  30 minutes cook time =  15 minutes yield =  Serves 4 variation =  For chilli mock duck: substitute mock duck for cheese cubes. Mock duck should be washed in hot water containing juice of half a lemon before cooking. Another variation is spicy beancurd: substitute deep fried cubes of soft beancurd for cheese cubes."
recipetext = "Tomato and Avocado Soup ingredients =  1 large or 2 small avocados 1 tin of tomatoes A good handful of fresh lovage Parsley to taste 1 stick of celery Small amount of sea salt 1 cup of apple juice 1 cup of water directions =  Place all the above in a blender and liquidise until smooth. Can be served chilled. tags =  cold dish soup raw vegetarian healthy nutritious gluten-free vegan prep time =  10 minutes cook time =  0 minutes yield =  4 servings per serving =  Highly nutritious, contains vitamins A, C and E"
scores = extract_timeline(recipetext, keyw)

In [161]:
print(scores)

{
    "relevance": 9,
    "groundedness": 10,
    "relatedness": 10,
    "semantic match": 9
}

In [151]:
df = df[:10]

In [162]:
scores_list = []
for index, row in df.iterrows():
    if index%20 == 0:
        print(index)
    query = row['query']
    text = row['text']
    distance = row['distance']
    id_ = row['id']
    scores = extract_timeline(text, query)
    scores = parse_chatgpt_json(scores)

    scores['query'] = query
    scores['text'] = text
    scores['distance'] = distance
    scores['id'] = id_
    scores_list.append(scores)

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640

In [163]:
scores_df = pd.DataFrame(scores_list)

In [164]:
scores_df.head(20)

,relevance,groundedness,relatedness,semantic match,query,text,distance,id
0,4,5,6,4,Paneer curry recipe,Paneer Tikka ingredients = 500 gms home-made ...,0.582293,309
1,3,3,4,2,Paneer curry recipe,Garbanzos and Potato Curry ingredients = 1 ti...,0.836615,324
2,2,2,3,2,Paneer curry recipe,thai coconut curry ingredients = 150 gms long...,0.878080,293
3,4,5,6,4,Paneer curry recipe,Baked Curry Rice ingredients = 3 cups long gr...,0.887982,343
4,2,2,3,2,Paneer curry recipe,Yogurt Curry ingredients = 8-10 chick pea flo...,0.904629,305
5,9,10,10,9,food items made with dal,Lentil Bonda ingredients = 115 gms urad dal (...,0.959076,234
6,9,10,10,9,food items made with dal,Spicy Lentil Crumble ingredients = 450 gms gr...,0.976582,245
7,1,1,1,1,food items made with dal,Chinese Mustard Dressing ingredients = 1 tabl...,1.040651,87
8,1,1,1,1,food items made with dal,Rice Noodle Caboodle ingredients = water 1 ta...,1.057738,869
9,2,2,3,2,food items made with dal,"Udon noodles with seitan, broccoli, and napa c...",1.061356,67
10,7,8,8,7,Indian Style Sandwich,bun bread sandwiches ingredients = bread buns...,0.807256,220
11,2,3,3,2,Indian Style Sandwich,Bombay Potatoes ingredients = 500 gms potatoe...,1.026896,291
12,8,9,9,7,Indian Style Sandwich,"Bread Rolls ingredients = 18 bread slices, no...",1.026902,243
13,3,3,4,2,Indian Style Sandwich,"Tomato, Spring Onion and Coriander Salad ingre...",1.058773,438
14,3,3,4,3,Indian Style Sandwich,Paneer Tikka ingredients = 500 gms home-made ...,1.058876,309
15,10,10,10,10,french fries recipes,Baked French Fries ingredients = 4 baking pot...,0.591338,693
16,3,3,4,3,french fries recipes,vegetable fritters ingredients = Your choice ...,0.828285,251
17,2,2,3,2,french fries recipes,"Curried potato, chickpea, and corn burgers ing...",0.855560,16
18,1,1,1,1,french fries recipes,Onion Cakes ingredients = 2 cups plain flour ...,0.858533,230
19,2,2,3,2,french fries recipes,Vegetable Cutlets ingredients = 500 gms potat...,0.863652,252

In [165]:
scores_df.shape

(645, 8)

In [166]:
scores_df.columns

Index(['relevance', 'groundedness', 'relatedness', 'semantic match', 'query',
       'text', 'distance', 'id'],
      dtype='str')

In [167]:
scores_df = scores_df[['query', 'text', 'relevance', 'groundedness', 'relatedness', 'semantic match', 'distance', 'id']]

In [169]:
vali = pd.read_csv('/home/linux/linux/ProjectsReal/chef/validation.csv')

In [170]:
vali.head()

                      Query   query type
0       Paneer curry recipe  ingredients
1  food items made with dal  ingredients
2     Indian Style Sandwich  ingredients
3      french fries recipes  ingredients
4    french onion soup tips  ingredients

In [171]:
scores_df_merged = scores_df.merge(vali, left_on="query", right_on="Query", how="left")

In [172]:
scores_df_merged.head()

,query,text,relevance,groundedness,relatedness,semantic match,distance,id,Query,query type
0,Paneer curry recipe,Paneer Tikka ingredients = 500 gms home-made ...,4,5,6,4,0.582293,309,Paneer curry recipe,ingredients
1,Paneer curry recipe,Garbanzos and Potato Curry ingredients = 1 ti...,3,3,4,2,0.836615,324,Paneer curry recipe,ingredients
2,Paneer curry recipe,thai coconut curry ingredients = 150 gms long...,2,2,3,2,0.878080,293,Paneer curry recipe,ingredients
3,Paneer curry recipe,Baked Curry Rice ingredients = 3 cups long gr...,4,5,6,4,0.887982,343,Paneer curry recipe,ingredients
4,Paneer curry recipe,Yogurt Curry ingredients = 8-10 chick pea flo...,2,2,3,2,0.904629,305,Paneer curry recipe,ingredients

In [173]:
scores_df_merged.drop(columns=["Query"], inplace=True)

In [174]:
scores_df_merged.head()

,query,text,relevance,groundedness,relatedness,semantic match,distance,id,query type
0,Paneer curry recipe,Paneer Tikka ingredients = 500 gms home-made ...,4,5,6,4,0.582293,309,ingredients
1,Paneer curry recipe,Garbanzos and Potato Curry ingredients = 1 ti...,3,3,4,2,0.836615,324,ingredients
2,Paneer curry recipe,thai coconut curry ingredients = 150 gms long...,2,2,3,2,0.878080,293,ingredients
3,Paneer curry recipe,Baked Curry Rice ingredients = 3 cups long gr...,4,5,6,4,0.887982,343,ingredients
4,Paneer curry recipe,Yogurt Curry ingredients = 8-10 chick pea flo...,2,2,3,2,0.904629,305,ingredients

In [175]:
scores_df_merged.to_csv('/home/linux/linux/ProjectsReal/chef/validation_extracted_scored_merged.csv', index=False)